"""FastAPI application: Titanic survival prediction demo web app.

The app exposes:
    GET  /                    -> interactive demo page (charts + prediction form)
    GET  /api/health          -> service health check
    GET  /api/summary         -> training summary (metrics of all 4 models)
    GET  /api/predictions     -> true vs predicted table of the test split
    POST /api/predict         -> predict one passenger (JSON body)
    GET  /api/predict?..      -> same prediction, but query-string friendly

All figures, CSVs and model pipelines are generated by `python -m titanic.train`.
On startup the app tries to load those pre-trained artifacts from disk
(outputs/ + models/) so it can answer immediately without retraining; if they
are missing it trains once on first request (lazy, cached in memory).

Run with:  uvicorn app:app --host 0.0.0.0 --port 8000
"""

from contextlib import asynccontextmanager

import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

from titanic import config
from titanic import train as trainer
from titanic.i18n import CHART_CAPTIONS, UI, pick as i18n_pick
from titanic.preprocessing import build_preprocessor, load_data, make_features

# Human-readable labels for the four models (id -> label)
MODEL_LABELS = dict(config.MODELS)


# ---------------------------------------------------------------------------
# Application lifecycle: load pre-trained artifacts once at startup
# ---------------------------------------------------------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    """On startup reuse artifacts produced by `python -m titanic.train`.

    If outputs/metrics_all_models.csv + models/pipeline_*.joblib already exist
    (the normal case after the pipeline ran once), loading them is instant and
    avoids retraining. Otherwise the trainer falls back to training lazily on
    the first API call (cached afterwards).
    """
    trainer.preprocessor = build_preprocessor()
    pipelines_dir = config.PROJECT_ROOT / "models"
    metrics_path = config.CSV_DIR / "metrics_all_models.csv"
    if metrics_path.exists():
        try:
            # 1. reload the four serialized pipelines
            for name, _ in config.MODELS:
                p = pipelines_dir / f"pipeline_{name}.joblib"
                if p.exists():
                    trainer._pipelines[name] = joblib.load(p)
            # 2. rebuild the in-memory metadata from the saved CSVs
            metrics_df = pd.read_csv(metrics_path)
            trainer._meta["metrics"] = metrics_df.to_dict(orient="records")
            trainer._meta["figures"] = {
                p.name: str(p) for p in sorted(config.FIG_DIR.glob("*.png"))
            }
            trainer._meta["best_model_id"] = str(
                metrics_df.loc[metrics_df["accuracy"].idxmax(), "model_id"]
            )
            # 3. rebuild test-set rows (ids/true/pred per model) from the first
            #    prediction CSV so /api/predictions works without retraining
            first_pred_csv = sorted(config.CSV_DIR.glob("predictions_*.csv"))
            if first_pred_csv:
                first = pd.read_csv(first_pred_csv[0])
                trainer._meta["n_rows"] = int(first.shape[0])  # test-set rows
                trainer._meta["test_ids"] = first["PassengerId"].tolist()
                trainer._meta["y_test"] = first["Survived_true"].tolist()
                trainer._meta["y_pred"] = {}
                for csv_file in first_pred_csv:
                    name = csv_file.name.removeprefix("predictions_").removesuffix(".csv")
                    df = pd.read_csv(csv_file)
                    trainer._meta["y_pred"][name] = df["Survived_pred"].tolist()
            print("[startup] Loaded trained pipelines + artifacts from disk.")
        except Exception as exc:  # corrupted artifact -> retrain lazily on demand
            trainer._pipelines.clear()
            print(f"[startup] Artifact reload failed ({exc}); will retrain on demand.")
    yield


app = FastAPI(
    title="Titanic Survival Prediction",
    description="AI course homework: predict Titanic survival + data visualization.",
    version="1.0.0",
    lifespan=lifespan,
)

# Serve static assets (CSS) and generated charts from their folders
app.mount("/static", StaticFiles(directory=config.STATIC_DIR), name="static")
app.mount("/figures", StaticFiles(directory=config.FIG_DIR), name="figures")

templates = Jinja2Templates(directory=str(config.TEMPLATE_DIR))


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _predict_from_row(row: dict, model_id: str | None = None) -> dict:
    """Predict survival for one passenger dict through a fitted pipeline.

    Args:
        row: feature dict with keys Pclass/Sex/Age/SibSp/Parch/Fare/Embarked.
        model_id: model key, or None -> use the best model of the training run.
    """
    meta = trainer.get_meta()
    if model_id is None or model_id not in trainer._pipelines:
        model_id = meta.get("best_model_id", "random_forest")
    pipe = trainer._pipelines[model_id]

    # Build a single-row feature frame (same columns/order as the training data)
    one = pd.DataFrame([row], columns=config.FORM_COLS)

    # Keep probability estimates robust for any model that can produce them;
    # tree/linear models all expose predict_proba through the pipeline.
    proba = pipe.predict_proba(one)[0]      # [P(not survived), P(survived)]
    survived_prob = float(proba[1])
    pred = int(pipe.predict(one)[0])
    return {
        "model_id": model_id,
        "model_label": MODEL_LABELS.get(model_id, model_id),
        "survived": pred,                   # 1 = survived, 0 = not survived
        "survived_probability": round(survived_prob, 4),
        "not_survived_probability": round(1 - survived_prob, 4),
        "prediction_text": "SURVIVED" if pred == 1 else "NOT SURVIVED",
    }


def _validate_payload(payload: dict) -> dict:
    """Validate/normalise a raw JSON body into a clean feature row."""
    try:
        row = {
            "Pclass": int(payload["Pclass"]),
            "Sex": str(payload["Sex"]).strip().lower(),
            "Age": float(payload.get("Age") or 30.0),
            "SibSp": int(payload.get("SibSp", 0)),
            "Parch": int(payload.get("Parch", 0)),
            "Fare": float(payload.get("Fare") or 32.0),
            "Embarked": str(payload.get("Embarked", "S")).strip().upper(),
        }
    except (KeyError, TypeError, ValueError) as exc:
        raise HTTPException(status_code=400, detail=f"Invalid payload: {exc}") from exc
    if row["Pclass"] not in (1, 2, 3):
        raise HTTPException(status_code=400, detail="Pclass must be 1, 2 or 3.")
    if row["Sex"] not in ("male", "female"):
        raise HTTPException(status_code=400, detail="Sex must be 'male' or 'female'.")
    if row["Embarked"] not in ("C", "Q", "S"):
        raise HTTPException(status_code=400, detail="Embarked must be 'C', 'Q' or 'S'.")
    if row["Age"] < 0 or row["Fare"] < 0:
        raise HTTPException(status_code=400, detail="Age/Fare cannot be negative.")
    return row


# ---------------------------------------------------------------------------
# routes
# ---------------------------------------------------------------------------

@app.get("/", response_class=HTMLResponse)
async def index(request: Request, lang: str = Query("en", pattern="^(en|zh)$")):
    """Render the demo dashboard (charts, metrics table, prediction form).

    ``?lang=en|zh`` selects the UI language (default en). Charts are
    bilingual PNGs so they work for both languages. The choice is stored in
    localStorage by the page and re-sent on every navigation.
    """
    meta = trainer.get_meta()
    # (file, url, caption) — caption follows the page language
    charts = [
        {
            "file": name,
            "url": f"/figures/{name}",
            "caption": CHART_CAPTIONS.get(name.removesuffix(".png"), ("", ""))[
                1 if lang == "zh" else 0
            ],
        }
        for name in sorted(meta.get("figures", {}))
    ]
    # expose every UI string: templates call t(key) / cap(key)
    def t(key: str) -> str:
        return i18n_pick(key, lang)

    def cap(key: str) -> str:
        en, zh_cn = CHART_CAPTIONS.get(key, ("", ""))
        return zh_cn if lang == "zh" else en

    return templates.TemplateResponse(
        request,  # new-style signature: (request, name, context)
        "index.html",
        {
            "lang": lang,
            "t": t,
            "cap": cap,
            "charts": charts,
            "metrics": meta.get("metrics", []),
            "best_model": meta.get("best_model_id", ""),
            "model_labels": MODEL_LABELS,
        },
    )


@app.get("/api/health")
async def health():
    """Simple health probe (used by the start script / smoke tests)."""
    return {"status": "ok", "service": "titanic-survival-api"}


@app.get("/api/summary")
async def summary():
    """Full training summary: metrics of every model + generated figures."""
    return JSONResponse(trainer.get_meta())


@app.get("/api/predictions")
async def predictions(model: str = Query("best", description="model id or 'best'")):
    """Test-split table: PassengerId + true label + predicted label (+ correctness)."""
    meta = trainer.get_meta()
    best = meta.get("best_model_id", "random_forest")
    model_id = best if model in ("best", "") else model
    if model_id not in trainer._pipelines:
        raise HTTPException(status_code=404, detail=f"Unknown model: {model_id}")
    table = pd.DataFrame(
        {
            "PassengerId": meta["test_ids"],
            "Survived_true": meta["y_test"],
            "Survived_pred": meta["y_pred"][model_id],
        }
    )
    table["Correct"] = (table["Survived_true"] == table["Survived_pred"]).astype(int)
    return JSONResponse(table.to_dict(orient="records"))


@app.post("/api/predict")
async def predict_post(payload: dict):
    """Predict survival for one passenger posted as a JSON body."""
    row = _validate_payload(payload)
    return _predict_from_row(row, payload.get("model"))


@app.get("/api/predict")
async def predict_get(request: Request):
    """Predict survival for one passenger via query parameters.

    Accepts both `Pclass` (HTML form field names) and `pclass` (canonical)
    spellings — FastAPI/HTTP query parameters are case-sensitive, and the
    demo form posts uppercase names, so we read them directly from the
    request to be safe against case mismatch.
    """
    q = request.query_params

    # pick the case-insensitive value; canonical lowercase wins if both given
    def pick(*names, default=None):
        for n in names:
            if n in q:
                return q[n]
        return default

    pclass_raw = pick("pclass", "Pclass")
    sex_raw = pick("sex", "Sex")
    age_raw = pick("age", "Age")
    sibsp_raw = pick("sibsp", "SibSp")
    parch_raw = pick("parch", "Parch")
    fare_raw = pick("fare", "Fare")
    embarked_raw = pick("embarked", "Embarked")
    model_raw = pick("model", "Model")

    # defaults mirror the HTML form
    try:
        pclass = int(pclass_raw) if pclass_raw is not None else 3
        sex = (sex_raw or "male").strip().lower()
        age = float(age_raw) if age_raw is not None else 30.0
        sibsp = int(sibsp_raw) if sibsp_raw is not None else 0
        parch = int(parch_raw) if parch_raw is not None else 0
        fare = float(fare_raw) if fare_raw is not None else 32.0
        embarked = (embarked_raw or "S").strip().upper()
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=f"Invalid number: {exc}") from exc

    row = {
        "Pclass": pclass,
        "Sex": sex,
        "Age": age,
        "SibSp": sibsp,
        "Parch": parch,
        "Fare": fare,
        "Embarked": embarked,
    }
    # light validation (same rules as the JSON endpoint)
    if pclass not in (1, 2, 3):
        raise HTTPException(status_code=400, detail="Pclass must be 1, 2 or 3.")
    if sex not in ("male", "female"):
        raise HTTPException(status_code=400, detail="Sex must be 'male' or 'female'.")
    if embarked not in ("C", "Q", "S"):
        raise HTTPException(status_code=400, detail="Embarked must be 'C', 'Q' or 'S'.")
    return _predict_from_row(row, model_raw)


# ---------------------------------------------------------------------------
# allow: python app.py  (convenient during development)
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import uvicorn

    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=False)
