"""Data understanding visualizations (saved to outputs/figures).

Every chart is deliberately simple (courseware style). Titles / axis labels /
legends are BILINGUAL (English + Simplified Chinese) so the same PNG works in
both the EN and the ZH page. A CJK font is auto-detected on the current
machine (YaHei / WenQuanYi / Noto CJK / Source Han / PingFang …); if none is
found the Chinese parts are dropped and the charts stay English-only, so the
figures never show tofu boxes on an unknown machine.

Charts (mirror of the courseware "data understanding" step):
    1_survived_counts       - target balance: survived vs not survived
    2_missing_values        - missing values per column (bar chart)
    3_sex_survival          - survival rate by sex
    4_pclass_survival       - survival rate by passenger class
    5_age_distribution      - age distribution by survival (histogram)
    6_fare_distribution     - fare distribution on log(1+Fare) scale
    7_model_comparison      - model comparison: grouped bars, five metrics
    8_roc_curves            - ROC curves for all models (AUC in legend)

Figures are (re)generated by train.py in one pipeline run and can also be
regenerated alone with:  python -m titanic.visualize
"""

from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # headless backend: no display needed, save to file
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from . import config
from .preprocessing import load_data

# ---------------------------------------------------------------------------
# CJK font handling — never print tofu boxes on any machine
# ---------------------------------------------------------------------------

# Candidate CJK font names, roughly ordered by likelihood on each platform.
_CJK_CANDIDATES = [
    "Microsoft YaHei",          # Windows
    "SimHei", "SimSun",         # Windows fallbacks
    "PingFang SC",              # macOS
    "Heiti SC", "STHeiti",
    "Noto Sans CJK SC",         # Linux / common
    "Noto Sans SC",
    "Source Han Sans SC",
    "Source Han Sans CN",
    "WenQuanYi Zen Hei",        # Linux fallbacks
    "WenQuanYi Micro Hei",
    "AR PL UMing CN",
]
_CJK_READY: bool | None = None   # cache: whether we found a CJK font


def _setup_cjk_font() -> bool:
    """Register a usable CJK font and return True if Chinese can be drawn."""
    global _CJK_READY
    if _CJK_READY is not None:
        return _CJK_READY
    from matplotlib import font_manager

    installed = {f.name for f in font_manager.fontManager.ttflist}
    chosen = next((n for n in _CJK_CANDIDATES if n in installed), None)
    if chosen is None:                       # none of the known fonts exist
        _CJK_READY = False
        return False
    # matplotlib >=3.7: rcParams["font.family"] accepts a list of families;
    # put the CJK font after the default sans stack so Latin stays default.
    plt.rcParams["font.sans-serif"] = [chosen, "DejaVu Sans",
                                       "Arial", "Helvetica", "sans-serif"]
    plt.rcParams["axes.unicode_minus"] = False  # minus sign renders fine
    _CJK_READY = True
    print(f"[visualize] CJK font in use: {chosen}")
    return True


def zh(text: str) -> str:
    """Return ``text`` only when a CJK font is available (else '').

    Used by :func:`_b` so charts never contain tofu boxes on machines
    without a Chinese font.
    """
    return text if _CJK_READY else ""


def _b(en: str, zh_cn: str) -> str:
    """Bilingual label: 'English\n中文' when CJK is available, else EN only."""
    return f"{en}\n{zh_cn}" if _CJK_READY else en


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _save(fig, name: str) -> Path:
    """Save a figure as PNG and close it to free memory."""
    out = config.FIG_DIR / f"{name}.png"
    fig.tight_layout()
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return out


# ---------------------------------------------------------------------------
# individual charts (labels are bilingual EN / 中文)
# ---------------------------------------------------------------------------

def chart_survived_counts(df: pd.DataFrame):
    """Bar chart: how many survived (1) vs not (0)."""
    counts = df["Survived"].value_counts().sort_index()  # index 0,1
    fig, ax = plt.subplots(figsize=(5.2, 4))
    bars = ax.bar([_b("Not survived", "未生还"), _b("Survived", "生还")],
                  counts, color=["#d95f5f", "#5fa8d9"])
    ax.bar_label(bars)  # print count on top of each bar
    ax.set_ylabel(_b("Number of passengers", "人数"))
    ax.set_title(_b("Target balance: survived vs not survived",
                     "目标变量分布：生还与未生还人数"))
    ax.grid(axis="y", alpha=0.3)
    return _save(fig, "1_survived_counts")


def chart_missing_values(df: pd.DataFrame):
    """Bar chart: number of missing (NaN) values per column."""
    missing = df.isna().sum()
    missing = missing[missing > 0].sort_values()  # keep only columns with NaN
    fig, ax = plt.subplots(figsize=(6, 4))
    ax.barh(missing.index, missing.values, color="#e0a458")  # horizontal bars
    for i, v in enumerate(missing.values):
        ax.text(v + 4, i, str(v), va="center")
    ax.set_xlabel(_b("Number of missing values", "缺失值数量"))
    ax.set_title(_b("Missing values per column", "各字段缺失值统计"))
    return _save(fig, "2_missing_values")


def _survival_rate_by_group(df: pd.DataFrame, col: str) -> pd.DataFrame:
    """Grouped survival rate table: rate per unique value of `col`."""
    grouped = df.groupby(col)["Survived"].agg(["mean", "count"])  # rate + size
    grouped["mean"] = grouped["mean"] * 100  # fraction -> percent
    return grouped.sort_values("mean", ascending=False)


def chart_sex_survival(df: pd.DataFrame):
    """Bar chart: survival rate for female vs male passengers."""
    rates = _survival_rate_by_group(df, "Sex")
    # keep the EN/中文 tick order stable: female first when present
    tick_labels = {"female": _b("Female", "女"), "male": _b("Male", "男")}
    labels = [tick_labels.get(str(v), str(v)) for v in rates.index]
    fig, ax = plt.subplots(figsize=(5.2, 4))
    bars = ax.bar(labels, rates["mean"],
                  color=["#5fa8d9", "#d95f5f"])
    ax.bar_label(bars, fmt="%.1f%%")  # percent on top of each bar
    ax.set_ylabel(_b("Survival rate (%)", "生还率(%)"))
    ax.set_title(_b("Survival rate by sex", "性别与生还率"))
    ax.set_ylim(0, 105)
    ax.grid(axis="y", alpha=0.3)
    return _save(fig, "3_sex_survival")


def chart_pclass_survival(df: pd.DataFrame):
    """Bar chart: survival rate for 1st / 2nd / 3rd class passengers."""
    rates = _survival_rate_by_group(df, "Pclass")
    labels = [_b(f"Class {v}", f"{v} 等舱") for v in rates.index]
    fig, ax = plt.subplots(figsize=(5.2, 4))
    bars = ax.bar(labels, rates["mean"], color="#7fb37f")
    ax.bar_label(bars, fmt="%.1f%%")
    ax.set_ylabel(_b("Survival rate (%)", "生还率(%)"))
    ax.set_title(_b("Survival rate by passenger class", "舱位等级与生还率"))
    ax.set_ylim(0, 105)
    ax.grid(axis="y", alpha=0.3)
    return _save(fig, "4_pclass_survival")


def chart_age_distribution(df: pd.DataFrame):
    """Histogram: age of survivors vs non-survivors (two overlaid series)."""
    survived = df.loc[df["Survived"] == 1, "Age"].dropna()
    not_survived = df.loc[df["Survived"] == 0, "Age"].dropna()
    fig, ax = plt.subplots(figsize=(6.4, 4))
    ax.hist([not_survived, survived], bins=20, stacked=False, alpha=0.55,
            label=[_b("Not survived", "未生还"), _b("Survived", "生还")],
            color=["#d95f5f", "#5fa8d9"])
    ax.set_xlabel(_b("Age", "年龄"))
    ax.set_ylabel(_b("Number of passengers", "人数"))
    ax.set_title(_b("Age distribution by survival", "年龄分布(按是否生还)"))
    ax.legend()
    return _save(fig, "5_age_distribution")


def chart_fare_distribution(df: pd.DataFrame):
    """Histogram: fare on the log(1+Fare) scale (courseware recommendation).

    Fare is heavily right-skewed, so we plot log(1+Fare). The +1 keeps the
    cheapest tickets (Fare == 0) at 0 instead of -inf.
    """
    log_fare = np.log1p(df["Fare"].dropna())  # ln(1 + Fare)
    fig, ax = plt.subplots(figsize=(6.4, 4))
    ax.hist(log_fare, bins=40, color="#9b8ec4")
    ax.set_xlabel(_b("log(1 + Fare)", "票价对数 log(1+Fare)"))
    ax.set_ylabel(_b("Number of passengers", "人数"))
    ax.set_title(_b("Fare distribution on log(1+Fare) scale",
                     "票价分布(log(1+Fare) 变换)"))
    ax.set_xlim(0, None)  # log(1+Fare) is always >= 0
    return _save(fig, "6_fare_distribution")


# ---------------------------------------------------------------------------
# model-comparison charts (added for courseware p.40 / p.44)
# ---------------------------------------------------------------------------

# id -> metric label (bilingual, drawn only when a CJK font exists)
_METRIC_LABELS = {
    "accuracy": ("Accuracy", "准确率"),
    "precision": ("Precision", "精确率"),
    "recall": ("Recall", "召回率"),
    "f1": ("F1", "F1 分数"),
    "auc": ("AUC", "AUC"),
}

# id -> color used for that model in every comparison chart
_MODEL_COLORS = {
    "logistic": "#5fa8d9",      # blue
    "svm": "#e0a458",           # gold
    "decision_tree": "#7fb37f",  # green
    "random_forest": "#d98c8c",  # soft red
}


def _model_short_label(model_id: str) -> str:
    """Very short tick label: LR / SVM / DT / RF."""
    return {"logistic": "LR", "svm": "SVM",
            "decision_tree": "DT", "random_forest": "RF"}.get(model_id, model_id)


def save_model_comparison_chart(metrics_df: pd.DataFrame,
                                roc_series: dict | None = None) -> list[Path]:
    """Draw the two courseware comparison charts and return their PNG paths.

    - ``roc_series=None``: grouped bar chart (courseware p.40) — for every
      metric (accuracy / precision / recall / F1 / AUC) one group of four
      bars, one bar per model. Every model has all five metrics side by side,
      which makes precision-vs-recall trade-offs visible at a glance.
    - ``roc_series`` given: ROC curves (courseware p.44) — one curve per
      model plus the chance diagonal; AUC is printed in the legend.
    """
    if roc_series is not None:
        return [_save(_draw_roc(roc_series), "8_roc_curves")]
    return [_save(_draw_metric_bars(metrics_df), "7_model_comparison")]


def _draw_metric_bars(metrics_df: pd.DataFrame) -> "plt.Figure":
    """Grouped bar chart: five metrics x four models (p.40)."""
    keys = config.METRIC_KEYS
    # align with the courseware table rows: keep the model order from config
    order = [mid for mid, _ in config.MODELS]
    frame = metrics_df.set_index("model_id").reindex(order)

    fig, ax = plt.subplots(figsize=(8.6, 4.6))
    n_models = len(order)
    width = 0.8 / n_models                    # total group width 0.8
    x = np.arange(len(keys))                  # one group per metric
    colors = [_MODEL_COLORS.get(mid, "#999") for mid in order]
    label_en = dict(config.MODELS)       # id -> full English label
    label_zh = {
        "logistic": "逻辑回归", "svm": "支持向量机",
        "decision_tree": "决策树", "random_forest": "随机森林",
    }
    for i, mid in enumerate(order):
        vals = frame.loc[mid, keys].astype(float).values
        bars = ax.bar(x + (i - n_models / 2 + 0.5) * width, vals, width,
                      label=_b(label_en.get(mid, mid), label_zh.get(mid, mid)),
                      color=colors[i])
        # tiny 3-digit labels above every bar
        ax.bar_label(bars, fmt="%.3f", fontsize=7, padding=1)

    ax.set_xticks(x)
    ax.set_xticklabels([_b(en, zh) for en, zh in
                        (_METRIC_LABELS[k] for k in keys)])
    ax.set_ylim(0, 1.06)
    ax.set_ylabel(_b("Score", "得分"))
    ax.set_title(_b("Model comparison on the test set (random_state=42)",
                    "四模型对比：测试集五指标(准确率/精确率/召回率/F1/AUC)"))
    ax.grid(axis="y", alpha=0.3)
    ax.legend(ncol=4, fontsize=9, framealpha=0.9)
    return fig


def _draw_roc(roc_series: dict) -> "plt.Figure":
    """ROC curves: one line per model + AUC in the legend (p.44)."""
    fig, ax = plt.subplots(figsize=(6.4, 5.2))
    order = [mid for mid, _ in config.MODELS]
    for mid in order:
        if mid not in roc_series:
            continue
        fpr, tpr = roc_series[mid]
        auc_val = float(np.trapezoid(tpr, fpr))  # same value the metric table shows
        ax.plot(fpr, tpr, lw=1.8, color=_MODEL_COLORS.get(mid, "#555"),
                label=f"{_model_short_label(mid)} (AUC={auc_val:.4f})")
    ax.plot([0, 1], [0, 1], "k--", lw=1, alpha=0.6,
            label=_b("Chance", "随机基线"))
    ax.set_xlabel(_b("False positive rate", "假正率 FPR"))
    ax.set_ylabel(_b("True positive rate", "真正率 TPR"))
    ax.set_title(_b("ROC curves — all models",
                    "ROC 曲线：四模型概率排序能力对比"))
    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(-0.02, 1.02)
    ax.grid(alpha=0.3)
    ax.legend(loc="lower right", fontsize=8.5)
    return fig


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------

def generate_all(data_path: Path | None = None) -> list[Path]:
    """Regenerate every visualization and return the list of PNG paths."""
    config.ensure_dirs()
    _setup_cjk_font()          # decide once whether Chinese labels are drawn
    df = load_data(data_path) if data_path else load_data()
    charts = [
        chart_survived_counts(df),
        chart_missing_values(df),
        chart_sex_survival(df),
        chart_pclass_survival(df),
        chart_age_distribution(df),
        chart_fare_distribution(df),
    ]
    return charts


if __name__ == "__main__":  # allow: python -m titanic.visualize
    config.ensure_dirs()
    generated = generate_all()
    print(f"Generated {len(generated)} charts into {config.FIG_DIR}")
    for p in generated:
        print(" -", p.name)
